### ISSUE TITLE
Different names for multiple switches (subtypes)?

### ISSUE THREAD

**Issue by justdun** [justme-1968/homebridge-fhem#100]
Hello!  

Thanks for the excellent plug in!  I have mine working with 6 switches and 4 sensor types. 

However, all the switches appear with the same siriName (and no reference to their subtype name).  

Is there a way to make the separate subtype switches identify with different names?  

Ideally they would appear with the siriName+subtype?

Thanks for the great work.

Justin.

**Comment by justme-1968** [comment]
that is how it is supposed to work. but: homekit ignores all external changes after the device is added for the first time. 

the easiest is to change the names in the home (or any other homekit) app.

**Comment by justdun** [comment]
Thanks for the replies. I have edited the names in Apple Home, but a lot of trial and error (and lockouts) trying to work out which switch was which.  I ended up having to watch the Homebridge logs to see which function each switch called to work out how to name each of them.  Would have been nice if Apple had implemented the subtypes properly.

Thanks for the great work!

Justin.
