### ISSUE TITLE
Problems with (new?) HomeMatic thermostats

### ISSUE THREAD

**Issue by Doridian** [justme-1968/homebridge-fhem#2]
- Thermostat has only status information on root device (desired-temperature, measured-temperature, battery are readable values)
- Thermostat has the control on DEVICE_Clima (also a copy of the readable values relevant to temperature)

-> Homebridge-FHEM detects it as a thermometer, not a thermostat, because it fails to find the controls

I manually changed Homebridge-FHEM to detect the sub channel as a full device (normally ignored), which makes it mostly work, except it is no longer capable of showing battery status.

Another thing I noticed: The mode in "climate" is "off" on HomeKit (but auto in FHEM and also displayed on the actual thermostats)

**Comment by justme-1968** [comment]
yes. this is known. you should use the fhem device that belongs to the climate channel and set the genericDeviceType to thermostat.

i'm still experimenting on merging readings from two fhem devices into one homekit service to get the battery state back. until then you can use a notify or a user reading to copy the battery reading also into the climate channel.

the modes are currently ignored as there is no really good 1:1 mapping from homekit modes to homematic modes. in the fhem forum was a diskussion about this but without a good solution as this matter is more complicated as it looks at the first glance. to change the mode you use the same command as for setting the temperature and setting the temperature changes the mode. sometimes in an non obvious way.

**Comment by justme-1968** [comment]
there is a beta of the new version available here: http://forum.fhem.de/index.php/topic,48558.msg402024.html#msg402024

it allows complete configuration/customization of the mapping from fhem readings to homekit characteristics/values and back.

**Comment by justme-1968** [comment]
i have just committed the new version and updated some docu. 

the thermostat should work automatically if you use the clima channel as the device. 

if this is not enough you can use the new config options to mix and match devices. this can also be used to create a custom configuration for the thermostat modes.
