### ISSUE TITLE
genericDeviceType for a contact sensor?

### ISSUE THREAD

**Issue by tobiasmuecksch** [justme-1968/homebridge-fhem#20]
I've bought a z-wave window sensor (made by a company called vision), which simply detects if a window/door is opened or closed. _(In my case the sensor detects if my flat's door is opened or closed)_. Sadly the window sensor is not supported out of the box. So I tried to configure it manually.

According to the readme there are the following genericDeviceTypes, ignore,switch,outlet,light,blind,thermostat,garage,window,lock

The only type, I thought might fit is *window*. So I tried *window*, but for some reason, home kit does not show it as a sensor, but as a window which in addition can be opened for a pickable percentage.

Which genericType should I pick? My Max! window sensor are recognized correctly, so I must have done something wrong...

Thank you in advance

**Comment by justme-1968** [comment]
the readme was not up to date. the current list ist security,ignore,switch,outlet,light,blind,thermometer,thermostat,contact,garage,window,lock and every known homekit service type from hap-nodejs/lib/gen/HomeKitTypes.js even if it is not in the list.

window is for electric windows. that is not what you want. you want a contact or ContactSensor.

then in homekitMapping you have to map ContactSensorState to something like this:
````
  ContactSensorState=contact,values=/^closed/:CONTACT_DETECTED;/.*/:CONTACT_NOT_DETECTED
````

if you also add a mapping for CurrentDoorState you will get a more intuitive display in eve and home and kann even ask siri vor opened or closed doors and windows:
````
  CurrentDoorState=contact,values=/^closed/:CLOSED;/.*/:OPEN
````

adjust the reading name and values according to your device.

**Comment by tobiasmuecksch** [comment]
@justme-1968 Thank you for the reply. I'm working on trying your solution. But somehow, I broke my home bridge. There is no error on the console, but in my home app for all devices there is a red notice "No Response"...

**Comment by justme-1968** [comment]
check the console output of homebridge, try eve and tap the warning triangle. there should be a better error message.

remove the mapping and check if it works again.

start homebridge with --debug and compare the output for the max sensor to the one you configured.

**Comment by tobiasmuecksch** [comment]
@justme-1968 Thank you very much. It works 😃!

Just FYI, how i fixed my home bridge:
I had to delete all folders in ~/.homebridge/ (what basically kills the cache).

**Comment by tobiasmuecksch** [comment]
One more question:

I tried to add the CurrentDoorState. But when I startup home bridge this error is on the console:

`[2016-09-30 14:42:17] [FHEM]   value: Unknown command {ReadingsVal("CLOSED, try help.Unknown command /.*/","OPEN","")}, try help.
  2016-09-30 14:42:17 caching: CLOSED;/.*/-OPEN: Unknown command {ReadingsVal("CLOSED, try help.Unknown command /.*/","OPEN","")}, try help.`

This is my homebridgeMapping (separated by **one** blank space):
`ContactSensorState=basicSet,values=/^.*0/:CONTACT_DETECTED;/.*/:CONTACT_NOT_DETECTED CurrentDoorState= basicSet,values=/^.*0/:CLOSED;/.*/:OPEN`

**Comment by tobiasmuecksch** [comment]
I already found it. Sorry! There was a blank space before "basicSet".
