### ISSUE TITLE
Nachdem Schalten Absturz von homebridge. Versuchtes npm Update failed

### ISSUE THREAD

**Issue by NetRat88** [justme-1968/homebridge-fhem#25]
Hi justme,

nachdem ich meinen harmonyhub in den Homekit Raum in fhem gelegt habe, stürzte homebridge nach dem Schalten einer Activity immer ab mit folgendem Fehler im Screenshot:
![screenshot_17](https://cloud.githubusercontent.com/assets/6528507/19498880/9b0bb18c-9593-11e6-82c4-c54c0cd7ef1a.png)

Nun muss ich aber gestehen, dass ich homebridge vor Ewigkeiten installiert und nicht mehr aktualisiert hatte. Deshalb habe ich zunächst auf meinem Raspberry Pi () das System aktualisiert mittel sudo update && sudo upgrade. Anschließend mittels sudo npm update -g homebridge versucht zu updaten und dabei folgende Fehler erhalten:

***********************************************************************************
/usr/local/bin/homebridge -> /usr/local/lib/node_modules/homebridge/bin/homebridge

> bignum@0.12.5 install /usr/local/lib/node_modules/homebridge/node_modules/bignum
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://rvagg-node.s3-us-west-2.amazonaws.com/bignum/v0.12.5/bignum-v0.12.5-node-v47-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for bignum@0.12.5 and node@5.0.0 (node-v47 ABI) (falling back to source compile with node-gyp) 
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/5.0.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/homebridge/node_modules/bignum/.node-gyp"
make: Entering directory '/usr/local/lib/node_modules/homebridge/node_modules/bignum/build'
make: *** No rule to make target '../.node-gyp/5.0.0/include/node/common.gypi', needed by 'Makefile'.  Stop.
make: Leaving directory '/usr/local/lib/node_modules/homebridge/node_modules/bignum/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.1.19+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/usr/local/lib/node_modules/homebridge/node_modules/bignum/binding/bignum.node" "--module_name=bignum" "--module_path=/usr/local/lib/node_modules/homebridge/node_modules/bignum/binding"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge/node_modules/bignum
gyp ERR! node -v v5.0.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/homebridge/node_modules/bignum/binding/bignum.node --module_name=bignum --module_path=/usr/local/lib/node_modules/homebridge/node_modules/bignum/binding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Linux 4.1.19+
node-pre-gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/homebridge/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /usr/local/lib/node_modules/homebridge/node_modules/bignum
node-pre-gyp ERR! node -v v5.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.30
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/usr/local/lib/node_modules/homebridge/node_modules/bignum/binding/bignum.node --module_name=bignum --module_path=/usr/local/lib/node_modules/homebridge/node_modules/bignum/binding' (1)
- curve25519@1.1.0 node_modules/homebridge/node_modules/curve25519
npm ERR! Linux 4.1.19+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "update" "-g" "homebridge"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE

npm ERR! bignum@0.12.5 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bignum@0.12.5 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the bignum package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls bignum
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/.homebridge/npm-debug.log
***********************************************************************************

Folgende Versionen werden verwendet:
node -v
v5.0.0
npm -v
3.3.6

Hast du einen Tipp, was ich tun kann und wo der Fehler liegt?
Gruß und Danke
NetRat88

**Comment by justme-1968** [comment]
dein upgrade ist unvollständig und da passen scheinbar gerade die versionen nicht zusammen.

installiert homebridge und homebridge-fhem am besten noch mal komplett drüber. das ist übrigens auch sonst meist das beste weil der upgrade manchmal nicht funktioniert.

````
npm install -g --unsafe-perm homebridge
npm install -g homebridge-fhem
````

**Comment by NetRat88** [comment]
Danke Dir! Ich habe gerade bemerkt, dass ich das Issue besser im homebridge rep direkt hätte machen sollen.
Aber nach einem sudo npm update -g npm && sudo npm update -g (anschließend npm Version 3.10.9) und erneuter Installation lief es durch. Auch mein Startskript und die Config blieben erhalten!

Homebridge läuft soweit ich das sehe nun auch stabil beim Schalten von den Harmony Aktivitäten über Siri!

Besten Dank, auch für diese großartige Arbeit! Weiter so!
Gruß
