### ISSUE TITLE
Proposal: Always show Max! Thermostats in heating mode

### ISSUE THREAD

**Issue by tobiasmuecksch** [justme-1968/homebridge-fhem#26]
Hey there,

after using Max! Thermostats with homebridge-fhem for a while, I'd like to propose a change in your automatic device configuration.

I think it would be more convenient for users to always show the thermostats in heating mode and (as it already is) ignore the changes made to the mode through homekit.

Currently the thermostats are shown as switched off. The home app then doesn't show the desired temperature in the overview. You always have to click and hold to see the desired temperature.

And additionally in my opinion it's more intuitive. Otherwise people can get confused.

**Comment by justme-1968** [comment]
that was not a problem with eve. it looks like home tries to be more intelligent.

does
```
CurrentHeatingCoolingState=default=HEAT 
```
in homebridgeMapping dies what you want?

**Comment by tobiasmuecksch** [comment]
I tried it three times.
When I add this homebridgeMapping line to one of my thermostats and then restart homebridge; homekit stops working. A red line "no response" appears below all my devices. When I remove the line and restart homebridge it still does not work.

I have to remove homebridge from my home app and then re-add it. But I can't re-add it without deleting the folders`~/.homebridge/accessories/` and `~/.homebridge/persist/` before restarting.

This happened all three times I tried it...

**Comment by justme-1968** [comment]
does it work if you provide a non existent reading:
```
CurrentHeatingCoolingState=xyz,default=HEAT 
```

if not please show the console output on homebridge start

**Comment by tobiasmuecksch** [comment]
@justme-1968 Yes. That works.

I'd propose that homebridge-fhem by default sets this automatically for all Thermostats.

**Comment by justme-1968** [comment]
i have just commited a change that should do this.

**Comment by tobiasmuecksch** [comment]
Thank you for the fix. But now all my thermostats show the red "no response".

I tried to re-add the homebridge and delete the persist and accessories folders but no success. But the thermostats show the right current temperature.

**Comment by justme-1968** [comment]
sorry. i did miss two other places that i had to fix to get this working.

now it should really be working.

**Comment by tobiasmuecksch** [comment]
It works! Thank you very much!
