### ISSUE TITLE
Thermostats - Desired temperature incorrect

### ISSUE THREAD

**Issue by tobiasmuecksch** [justme-1968/homebridge-fhem#27]
Hello,

sorry, for opening so many issues...
There still is a problem with my thermostats.

In the home app, an incorrect desired temperature is shown. In FHEM the temperature for all my thermostats is 18°C but in the app all thermostats are in an old state (all above 20°C).

When I change the temperature in HomeKit it correctly is changed in FHEM (and on the thermostats). But when I change the temperature on a thermostat it only is correctly synced to FEHM but not to homekit. It stays on the old state.

Currently I do not have any custom homebridgeMappings.

Example:

![img_0345](https://cloud.githubusercontent.com/assets/1294854/19884013/c2acfc76-a017-11e6-9e12-73b69161a015.PNG)

![bildschirmfoto 2016-11-01 um 09 35 30](https://cloud.githubusercontent.com/assets/1294854/19883941/4186bcea-a017-11e6-9bda-81dcb738e490.png)

Jsonlist2 for "Große Heizung" in room "Büro".
```
{ 
  "Arg":"MAX_03975d", 
  "Results": [ 
  { 
    "Name":"MAX_03975d", 
    "PossibleSets":"wakeUp factoryReset groupid associate:MAX_035278,MAX_093d63,MAX_0716a6,MAX_071689,MAX_067ab2,MAX_10d785,MAX_0746ff deassociate:MAX_035278,MAX_093d63,MAX_0716a6,MAX_071689,MAX_067ab2,MAX_10d785,MAX_0746ff desiredTemperature:eco,comfort,boost,auto,off,5.0,5.5,6.0,6.5,7.0,7.5,8.0,8.5,9.0,9.5,10.0,10.5,11.0,11.5,12.0,12.5,13.0,13.5,14.0,14.5,15.0,15.5,16.0,16.5,17.0,17.5,18.0,18.5,19.0,19.5,20.0,20.5,21.0,21.5,22.0,22.5,23.0,23.5,24.0,24.5,25.0,25.5,26.0,26.5,27.0,27.5,28.0,28.5,29.0,29.5,30.0,on ecoTemperature:off,5.0,5.5,6.0,6.5,7.0,7.5,8.0,8.5,9.0,9.5,10.0,10.5,11.0,11.5,12.0,12.5,13.0,13.5,14.0,14.5,15.0,15.5,16.0,16.5,17.0,17.5,18.0,18.5,19.0,19.5,20.0,20.5,21.0,21.5,22.0,22.5,23.0,23.5,24.0,24.5,25.0,25.5,26.0,26.5,27.0,27.5,28.0,28.5,29.0,29.5,30.0,on comfortTemperature:off,5.0,5.5,6.0,6.5,7.0,7.5,8.0,8.5,9.0,9.5,10.0,10.5,11.0,11.5,12.0,12.5,13.0,13.5,14.0,14.5,15.0,15.5,16.0,16.5,17.0,17.5,18.0,18.5,19.0,19.5,20.0,20.5,21.0,21.5,22.0,22.5,23.0,23.5,24.0,24.5,25.0,25.5,26.0,26.5,27.0,27.5,28.0,28.5,29.0,29.5,30.0,on measurementOffset:-3.5,-3.0,-2.5,-2.0,-1.5,-1.0,-0.5,0.0,0.5,1.0,1.5,2.0,2.5,3.0,3.5 maximumTemperature:off,5.0,5.5,6.0,6.5,7.0,7.5,8.0,8.5,9.0,9.5,10.0,10.5,11.0,11.5,12.0,12.5,13.0,13.5,14.0,14.5,15.0,15.5,16.0,16.5,17.0,17.5,18.0,18.5,19.0,19.5,20.0,20.5,21.0,21.5,22.0,22.5,23.0,23.5,24.0,24.5,25.0,25.5,26.0,26.5,27.0,27.5,28.0,28.5,29.0,29.5,30.0,on minimumTemperature:off,5.0,5.5,6.0,6.5,7.0,7.5,8.0,8.5,9.0,9.5,10.0,10.5,11.0,11.5,12.0,12.5,13.0,13.5,14.0,14.5,15.0,15.5,16.0,16.5,17.0,17.5,18.0,18.5,19.0,19.5,20.0,20.5,21.0,21.5,22.0,22.5,23.0,23.5,24.0,24.5,25.0,25.5,26.0,26.5,27.0,27.5,28.0,28.5,29.0,29.5,30.0,on windowOpenTemperature:off,5.0,5.5,6.0,6.5,7.0,7.5,8.0,8.5,9.0,9.5,10.0,10.5,11.0,11.5,12.0,12.5,13.0,13.5,14.0,14.5,15.0,15.5,16.0,16.5,17.0,17.5,18.0,18.5,19.0,19.5,20.0,20.5,21.0,21.5,22.0,22.5,23.0,23.5,24.0,24.5,25.0,25.5,26.0,26.5,27.0,27.5,28.0,28.5,29.0,29.5,30.0,on windowOpenDuration boostDuration:15,5,10,30,0,25,60,20 boostValveposition decalcification maxValveSetting valveOffset weekProfile", 
    "PossibleAttrs":"alias comment:textField-long eventMap group room suppressReading userReadings:textField-long verbose:0,1,2,3,4,5 IODev do_not_notify:1,0 ignore:0,1 dummy:0,1 showtime:1,0 keepAuto:0,1 scanTemp:0,1 event-on-change-reading event-on-update-reading event-aggregator event-min-interval stateFormat:textField-long timestamp-on-change-reading alarmDevice:Actor,Sensor alarmSettings cmdIcon devStateIcon devStateStyle genericDeviceType:ignore,switch,outlet,light,blind,thermometer,thermostat,garage,window,lock homebridgeMapping:textField-long icon sortby webCmd widgetOverride userattr", 
    "Internals": { 
      "DEF": "HeatingThermostat 03975d", 
      "LASTInputDev": "ml", 
      "MSGCNT": "2343", 
      "NAME": "MAX_03975d", 
      "NR": "29", 
      "STATE": "18.0 °C", 
      "TYPE": "MAX", 
      "addr": "03975d", 
      "backend": "ml", 
      "dstsetting": "1", 
      "ml_MSGCNT": "2343", 
      "ml_TIME": "2016-11-01 09:39:22", 
      "mode": "0", 
      "rferror": "0", 
      "serial": "IHA0022504", 
      "type": "HeatingThermostat" 
    }, 
    "Readings": { 
      "MAXLAN_error": { "Value":"0", "Time":"2016-11-01 09:39:22" }, 
      "MAXLAN_errorInCommand": { "Value":"", "Time":"2016-11-01 09:39:22" }, 
      "MAXLAN_initialized": { "Value":"1", "Time":"2016-11-01 09:39:22" }, 
      "MAXLAN_isAnswer": { "Value":"0", "Time":"2016-11-01 09:39:22" }, 
      "MAXLAN_valid": { "Value":"1", "Time":"2016-11-01 09:39:22" }, 
      "battery": { "Value":"ok", "Time":"2016-11-01 09:39:22" }, 
      "boostDuration": { "Value":"15", "Time":"2016-11-01 03:23:30" }, 
      "boostValveposition": { "Value":"80", "Time":"2016-11-01 03:23:30" }, 
      "comfortTemperature": { "Value":"21.0", "Time":"2016-11-01 03:23:30" }, 
      "decalcification": { "Value":"Sat 12:00", "Time":"2016-11-01 03:23:30" }, 
      "desiredTemperature": { "Value":"18.0", "Time":"2016-11-01 09:39:22" }, 
      "ecoTemperature": { "Value":"16.5", "Time":"2016-11-01 03:23:30" }, 
      "firmware": { "Value":"1.4", "Time":"2016-11-01 03:23:29" }, 
      "groupid": { "Value":"1", "Time":"2016-11-01 03:23:29" }, 
      "maxValveSetting": { "Value":"100", "Time":"2016-11-01 03:23:30" }, 
      "maximumTemperature": { "Value":"on", "Time":"2016-11-01 03:23:30" }, 
      "measurementOffset": { "Value":"0.0", "Time":"2016-11-01 03:23:30" }, 
      "minimumTemperature": { "Value":"off", "Time":"2016-11-01 03:23:30" }, 
      "mode": { "Value":"auto", "Time":"2016-11-01 09:39:22" }, 
      "state": { "Value":"18.0 °C", "Time":"2016-11-01 09:39:22" }, 
      "temperature": { "Value":"23.0", "Time":"2016-11-01 09:39:22" }, 
      "testresult": { "Value":"255", "Time":"2016-11-01 03:23:29" }, 
      "valveOffset": { "Value":"0", "Time":"2016-11-01 03:23:30" }, 
      "valveposition": { "Value":"0", "Time":"2016-11-01 09:39:22" }, 
      "weekprofile-0-Sat-temp": { "Value":"18.0 °C  /  21.0 °C  /  18.0 °C", "Time":"2016-11-01 03:23:30" }, 
      "weekprofile-0-Sat-time": { "Value":"00:00-06:05  /  06:05-22:00  /  22:00-00:00", "Time":"2016-11-01 03:23:30" }, 
      "weekprofile-1-Sun-temp": { "Value":"18.0 °C  /  21.0 °C  /  18.0 °C", "Time":"2016-11-01 03:23:30" }, 
      "weekprofile-1-Sun-time": { "Value":"00:00-06:05  /  06:05-22:00  /  22:00-00:00", "Time":"2016-11-01 03:23:30" }, 
      "weekprofile-2-Mon-temp": { "Value":"18.0 °C  /  21.0 °C  /  18.0 °C  /  21.0 °C  /  18.0 °C", "Time":"2016-11-01 03:23:30" }, 
      "weekprofile-2-Mon-time": { "Value":"00:00-06:05  /  06:05-09:00  /  09:00-17:05  /  17:05-23:00  /  23:00-00:00", "Time":"2016-11-01 03:23:30" }, 
      "weekprofile-3-Tue-temp": { "Value":"18.0 °C  /  21.0 °C  /  18.0 °C  /  21.0 °C  /  18.0 °C", "Time":"2016-11-01 03:23:30" }, 
      "weekprofile-3-Tue-time": { "Value":"00:00-06:05  /  06:05-09:00  /  09:00-17:05  /  17:05-23:00  /  23:00-00:00", "Time":"2016-11-01 03:23:30" }, 
      "weekprofile-4-Wed-temp": { "Value":"18.0 °C  /  21.0 °C  /  18.0 °C  /  21.0 °C  /  18.0 °C", "Time":"2016-11-01 03:23:30" }, 
      "weekprofile-4-Wed-time": { "Value":"00:00-06:05  /  06:05-09:00  /  09:00-17:05  /  17:05-23:00  /  23:00-00:00", "Time":"2016-11-01 03:23:30" }, 
      "weekprofile-5-Thu-temp": { "Value":"18.0 °C  /  21.0 °C  /  18.0 °C  /  21.0 °C  /  18.0 °C", "Time":"2016-11-01 03:23:30" }, 
      "weekprofile-5-Thu-time": { "Value":"00:00-06:05  /  06:05-09:00  /  09:00-17:05  /  17:05-23:00  /  23:00-00:00", "Time":"2016-11-01 03:23:30" }, 
      "weekprofile-6-Fri-temp": { "Value":"18.0 °C  /  21.0 °C  /  18.0 °C  /  21.0 °C  /  18.0 °C", "Time":"2016-11-01 03:23:30" }, 
      "weekprofile-6-Fri-time": { "Value":"00:00-06:05  /  06:05-09:00  /  09:00-17:05  /  17:05-23:00  /  23:00-00:00", "Time":"2016-11-01 03:23:30" }, 
      "windowOpenDuration": { "Value":"15", "Time":"2016-11-01 03:23:30" }, 
      "windowOpenTemperature": { "Value":"12.0", "Time":"2016-11-01 03:23:30" } 
    }, 
    "Attributes": { 
      "IODev": "ml", 
      "alias": "Große Heizung", 
      "icon": "hc_wht_regler", 
      "room": "Büro,MAX" 
    } 
  }  ], 
  "totalResultsReturned":1 
} 

```

**Comment by justme-1968** [comment]
are the values wrong directly after homebridge start?

please check if the homekit values are updated correctly if you use setreading to change the reading value:
''''
setreading MAX_03975d desiredTemperature 10
''''

please compare to the console messages and also to eve.

**Comment by tobiasmuecksch** [comment]
Yes,

```
setreading MAX_03975d desiredTemperature 10
```

works as expected. That's strange!


Console output for setreading:
```
2016-11-01 10:40:08 caching: MAX_03975d-desiredTemperature: 10
[2016-11-01 10:40:08] [FHEM]     caching: TargetTemperature: 10 (as number; from '10')
```

But there is no console output for updated desiredTemperature by Max!
I guess homebridge does not realize that the reading has changed.

**Comment by tobiasmuecksch** [comment]
Nope, the plugin update doesn't fix it...

**Comment by justme-1968** [comment]
if setreading works and the other not then the homebridge side is ok and there is some event issue on the fhem side.

open two browser windows and check if one gets correctly updated if you use the dropdown in the other. also check if the event monitor shows the event and if the device detail view is updated (red timestamp).

if not: please report it as a bug in the max module.

**Comment by tobiasmuecksch** [comment]
Okay, I will close this issue as soon as it is resolved.

> if not: please report it as a bug in the max module.

Do you mean the forum, or is there a specific issue tracker?

**Comment by tobiasmuecksch** [comment]
I've updated the plugin to the newest version.
After further investigation I found out that change events are thrown again.
But the FHEM GUI still doesn't update as expected...

See:
![bildschirmfoto 2016-11-06 um 14 12 17](https://cloud.githubusercontent.com/assets/1294854/20037959/338b43b4-a42b-11e6-9e43-8932ef605fbe.png)


But homekit still doesn't update correctly. I found out, that the current temperature isn't reflected correctly too.

So I guess there must be some sort of bug in homebridge-fhem

**Comment by justme-1968** [comment]
you say the events are visible in the event monitor but fhemweb itself will not update the readings in the device detail view? 

is the event visible in the homebridge console output?

**Comment by tobiasmuecksch** [comment]
> you say the events are visible in the event monitor but fhemweb itself will not update the readings in the device detail view?

yes

> is the event visible in the homebridge console output?

I just restarted homebrige with --debug flag and waited. The max thermostat events that a shown in the fhem event monitor are not shown in homebridge console output. There is no reaction at all. There only is the following message reappearing every ~20 seconds:

```
starting longpoll: http://127.0.0.1:8083/fhem.pl?XHR=1&inform=type=status;addglobal=1;filter=.*;since=null;fmt=JSON&timestamp=1478553387341
```

I guess that's normal.

**Comment by justme-1968** [comment]
if fhemweb is also not updating automatically then it is not only a homebridge problem. but i have currently no idea what it is. please have a look at the javascript console of your browser. are there any error in the device detail page if such an event comes in?

longpoll should not be retarted every 20 seconds but a connection should last for hours or days.

there is something wrong...

**Comment by tobiasmuecksch** [comment]
![bildschirmfoto 2016-11-08 um 10 14 04](https://cloud.githubusercontent.com/assets/1294854/20093208/1cd2b25c-a59c-11e6-9996-c3a22868bd35.png)

**Comment by tobiasmuecksch** [comment]
Well, I do have a second fhem & homebridge on another raspberry pi.
The re-polling issue doesn't appear there (it doesn't have any Max! devices).

So I guess no there are two possible error sources:

- messed up configuration, so it's some how my fault
- broken Max! plug-in

In order to rule out the second option, I will remove the max_lan device from the broken instance and add it to the working instance. If the problem doesn't re-appear on the other instance, I have to assume it's my fault. So I will reinstall the whole raspbian (including FHEM and homebridge).

**Comment by tobiasmuecksch** [comment]
After removing the max_lan device, the re-polling issue disappeared...

**Comment by justme-1968** [comment]
could you please check if fhem is blocked before the reconnect happens?

**Comment by tobiasmuecksch** [comment]
Do you mean the message "Connection lost. Trying again in 5 seconds"?

**Comment by justme-1968** [comment]
yes

**Comment by tobiasmuecksch** [comment]
Yes it appears in most of the connection loss cases

**Comment by tobiasmuecksch** [comment]
I think it's an max_lan (ml) issue. So I'm going to close this issue and I will try to use a CUL or CUNO instead.
