### ISSUE TITLE
longpoll ended

### ISSUE THREAD

**Issue by solbadguy2010** [justme-1968/homebridge-fhem#31]
Hello,
i have a very strange behavior with my FHEM and Homebridge. I use a MAX Cube with FHEM. I have 3 rooms with thermostats and window sensors. All of them are working completely fine with homebridge-fhem. I see if a windows is openend or closed, a temperture is changed and i can change temperatures from my iphone as well. My problem starts when i open windows in more than one room. the second thermostats then will switch to eco temperature and afterwards nothing is updating in iOS anymore. Log shows then:

`  2017-07-19 23:01:03 caching: Heizung.Schlafzimmer-desiredTemperature: 19.0`
`[7/19/2017, 11:01:03 PM] [FHEM]     caching: TargetTemperature: 19 (as number; from '19.0')`
`  2017-07-19 23:01:03 caching: Heizung.Schlafzimmer-temperature: 25.2`
`[7/19/2017, 11:01:03 PM] [FHEM]     caching: CurrentTemperature: 25.2 (as number; from '25.2')`
`  2017-07-19 23:03:04 caching: Wandthermostat.Kamin-temperature: 25.2`
`[7/19/2017, 11:03:04 PM] [FHEM]     caching: CurrentTemperature: 25.2 (as number; from '25.2')`
`[7/19/2017, 11:03:30 PM] [FHEM] query: TargetTemperature for Heizung.Bad-desiredTemperature`
`[7/19/2017, 11:03:30 PM] [FHEM]   cached: 16 (as number')`
`[7/19/2017, 11:03:30 PM] [FHEM] query: CurrentTemperature for Heizung.Bad-temperature`
`[7/19/2017, 11:03:30 PM] [FHEM]   cached: 23.3 (as number')`
`[7/19/2017, 11:03:30 PM] [FHEM] query: StatusLowBattery for Heizung.Bad-battery`
`[7/19/2017, 11:03:30 PM] [FHEM]   cached: 0 (as number; means BATTERY_LEVEL_NORMAL')`
`[7/19/2017, 11:03:30 PM] [FHEM] query: CurrentHeatingCoolingState for Heizung.Bad-undefined`
`[7/19/2017, 11:03:30 PM] [FHEM]   cached: 1 (as number; means HEAT')`
`[7/19/2017, 11:03:30 PM] [FHEM] query: StatusLowBattery for Fenster.Oben-battery`
`[7/19/2017, 11:03:30 PM] [FHEM]   cached: 0 (as number; means BATTERY_LEVEL_NORMAL')`
`[7/19/2017, 11:03:30 PM] [FHEM] query: ContactSensorState for Fenster.Oben-state`
`[7/19/2017, 11:03:30 PM] [FHEM]   cached: 1 (as number; means CONTACT_NOT_DETECTED')`
`[7/19/2017, 11:03:30 PM] [FHEM] query: CurrentHeatingCoolingState for Wandthermostat.Kamin-undefined`
`[7/19/2017, 11:03:30 PM] [FHEM]   cached: 1 (as number; means HEAT')`
`[7/19/2017, 11:03:30 PM] [FHEM] query: TargetTemperature for Wandthermostat.Kamin-desiredTemperature`
`[7/19/2017, 11:03:30 PM] [FHEM]   cached: 10 (as number')`
`[7/19/2017, 11:03:30 PM] [FHEM] query: CurrentTemperature for Wandthermostat.Kamin-temperature`
`[7/19/2017, 11:03:30 PM] [FHEM]   cached: 25.2 (as number')`
`[7/19/2017, 11:03:30 PM] [FHEM] query: StatusLowBattery for Wandthermostat.Kamin-battery`
`[7/19/2017, 11:03:30 PM] [FHEM]   cached: 0 (as number; means BATTERY_LEVEL_NORMAL')`
`[7/19/2017, 11:03:30 PM] [FHEM] query: CurrentHeatingCoolingState for Heizung.Schlafzimmer-undefined`
`[7/19/2017, 11:03:30 PM] [FHEM]   cached: 1 (as number; means HEAT')`
`[7/19/2017, 11:03:30 PM] [FHEM] query: CurrentTemperature for Heizung.Schlafzimmer-temperature`
`[7/19/2017, 11:03:30 PM] [FHEM]   cached: 25.2 (as number')`
`[7/19/2017, 11:03:30 PM] [FHEM] query: TargetTemperature for Heizung.Schlafzimmer-desiredTemperature`
`[7/19/2017, 11:03:30 PM] [FHEM]   cached: 19 (as number')`
`[7/19/2017, 11:03:30 PM] [FHEM] query: StatusLowBattery for Heizung.Schlafzimmer-battery`
`[7/19/2017, 11:03:30 PM] [FHEM]   cached: 0 (as number; means BATTERY_LEVEL_NORMAL')`
`[7/19/2017, 11:03:30 PM] [FHEM] query: StatusLowBattery for Fenster.Balkon-battery`
`[7/19/2017, 11:03:30 PM] [FHEM]   cached: 0 (as number; means BATTERY_LEVEL_NORMAL')`
`[7/19/2017, 11:03:30 PM] [FHEM] query: ContactSensorState for Fenster.Balkon-state`
`[7/19/2017, 11:03:30 PM] [FHEM]   cached: 1 (as number; means CONTACT_NOT_DETECTED')`
`  2017-07-19 23:04:04 caching: Heizung.Schlafzimmer-desiredTemperature: 10.0`
`[7/19/2017, 11:04:04 PM] [FHEM]     caching: TargetTemperature: 10 (as number; from '10.0')`
`  2017-07-19 23:04:04 caching: Fenster.Schlafzimmer-state: opened`
`[7/19/2017, 11:04:04 PM] [FHEM]     caching: ContactSensorState: 1 (as number; means CONTACT_NOT_DETECTED; from 'opened')`
`[7/19/2017, 11:04:04 PM] [FHEM]     caching: CurrentDoorState: 0 (as number; means OPEN; from 'opened')`
`longpoll ended, reconnect in: 200msec`
`starting longpoll: https://10.0.1.10:8083/fhem?XHR=1&inform=type=status;addglobal=1;filter=.*;since=1500498364.464;fmt=JSON&timestamp=1500498424853`
`[7/19/2017, 11:07:04 PM] [FHEM] Checking devices and attributes...`
`[7/19/2017, 11:07:04 PM] [FHEM]   executing: https://10.0.1.10:8083/fhem?cmd=%7BAttrVal(%22global%22,%22userattr%22,%22%22)%7D&fwcsrf=csrf_87503770529008&XHR=1`
`[7/19/2017, 11:07:04 PM] [FHEM]   executing: https://10.0.1.10:8083/fhem?cmd=jsonlist2%20TYPE=siri&fwcsrf=csrf_87503770529008&XHR=1`
`[7/19/2017, 11:07:05 PM] [FHEM] siri device is siri`
`[7/19/2017, 11:07:05 PM] [FHEM]   executing: https://10.0.1.10:8083/fhem?cmd=%7B$defs%7Bsiri%7D-%3E%7B%22homebridge-fhem%20version%22%7D%20=%20%220.3.7%22%7D&fwcsrf=csrf_87503770529008&XHR=1`
`longpoll ended, reconnect in: 200msec
`starting longpoll: https://10.0.1.10:8083/fhem?XHR=1&inform=type=status;addglobal=1;filter=.*;since=1500498364.464;fmt=JSON&timestamp=1500498484971`
`[7/19/2017, 11:08:05 PM] [FHEM] Checking devices and attributes...`
`[7/19/2017, 11:08:05 PM] [FHEM]   executing: https://10.0.1.10:8083/fhem?cmd=%7BAttrVal(%22global%22,%22userattr%22,%22%22)%7D&fwcsrf=csrf_87503770529008&XHR=1`
`[7/19/2017, 11:08:05 PM] [FHEM]   executing: https://10.0.1.10:8083/fhem?cmd=jsonlist2%20TYPE=siri&fwcsrf=csrf_87503770529008&XHR=1`
`[7/19/2017, 11:08:05 PM] [FHEM] siri device is siri`
`[7/19/2017, 11:08:05 PM] [FHEM]   executing: https://10.0.1.10:8083/fhem?cmd=%7B$defs%7Bsiri%7D-%3E%7B%22homebridge-fhem%20version%22%7D%20=%20%220.3.7%22%7D&fwcsrf=csrf_87503770529008&XHR=1`
`longpoll ended, reconnect in: 200msec`

again and again and again. The behavior stops when i close the windows in all rooms and restart homebridge. While this is happening everything inside FHEM is working normal. Only the longpoll of homebridge-fhem is crashing.

Can you please help me to fix this? Am i doing anything wrong?

**Comment by volschin** [comment]
I think you should grab the json from fhem before and after you opened the windows. Then you can compare both files to see if there is something unusual in change.

**Comment by solbadguy2010** [comment]
I found a Solution that worked for me. Before i had two radiator thermostats and, for the living room, a wall thermostat in the homebridge room in fhem. I exchanged the wall thermostat wit one of the radiators in the living room and now everything runs just fine.
