### ISSUE TITLE
Setlist on off vs ON OFF (Sonoff)

### ISSUE THREAD

**Issue by maddhin** [justme-1968/homebridge-fhem#33]
Hi,

I just installed my first Sonoff (through a dummy & notify) and found the problem that when I set "setlist ON OFF", Homebridge is not working. Only "setlist on off" works. 

As the Sonoff devices set the state as ON and OFF, it would be ideal to also use ON OFF in setlist. Otherwise one need to change the devStateIcon etc. 

A bit of a luxury problem... :) Thanks!

Edit: one of the problems here is that Homebridge actually also sets the state to "on" and "off" in the device which can be problematic for notifies etc.

**Comment by maddhin** [comment]
eventMap ON:on OFF:off solved the issue for me. One doesn't need a dummy either.

**Comment by justme-1968** [comment]
another way to handle this is to use a homebridgeMapping with On=state,valueOn=ON,valueOff=OFF.

**Comment by maddhin** [comment]
Many thanks! I also found that solution after some searching and would have used if eventMap didn't work. 
I would recommend to add such a simple example into the documentation - the examples are very good but it was difficult for me to do this mapping for the simple switch haha 

Thanks for your work!
