### ISSUE TITLE
Logs should use platform.log instead of console.log 

### ISSUE THREAD

**Issue by volschin** [justme-1968/homebridge-fhem#36]
The latest sample for plugin development suggests to not use console.log anymore directly.

This would be helpful to deal with formats like with timestamp or not and the way the plugin prefix is outputed.

**Comment by justme-1968** [comment]
the only console.log statements used in the latest version are outside of accessory and plugin contexts. so there is no plugin context and i don't have a homebridge log object to use at this point.

also you can have more than one fhem plugin active at the same time and caching one of the them would result in confusion as the log message is not related to any plugin.
