### ISSUE TITLE
Cannot add without desired-temp

### ISSUE THREAD

**Issue by tillsteinbach** [justme-1968/homebridge-fhem#4]
When there is no desired-temp reported at one of my FHTs I cannot add the homebridge accessory. Probably HomeKit checks for a desired-temp property. Might be useful to just fake a temperature (0?).

**Comment by tillsteinbach** [comment]
Looks like the same applies to the ROOMMATE module if there is no state set

**Comment by justme-1968** [comment]
there is a beta of the new version available here: http://forum.fhem.de/index.php/topic,48558.msg402024.html#msg402024

it allows complete configuration/customization of the mapping from fhem readings to homekit characteristics/values and back.

**Comment by tillsteinbach** [comment]
Do I have to register in the forum to see the beta? Why not using a development branch instead?

**Comment by justme-1968** [comment]
i have just committed the new version and updated some docu. with the new config options you should be able to get devices without readings working.
