### ISSUE TITLE
Waterlevel > Humidity

### ISSUE THREAD

**Issue by theo-69** [justme-1968/homebridge-fhem#42]
Hi there I am trying to figure out how I can bring my proteus TEK603 Water-level Reader into homebridge. It shows one of the measurements in %

`Internals: 
   DEF        /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0 
   DeviceName /dev/serial/by-id/usb-Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001-if00-port0 
   FD         82 
   NAME       ecometer 
   NR         1196 
   PARTIAL 
   PORTSTATE  open 
   STATE      opened 
   TYPE       TEK603 
   buffer     5349001602100b0904e75dde6200000010b71cbde266 
   READINGS: 
     2017-11-03 09:38:24   RemainingUsableLevel 4279 
     2017-11-03 09:38:24   RemainingUsablePercent 58.2 
     2017-11-03 09:38:24   Temperature     18.89 
     2017-11-03 09:38:24   Time            10:39:03 
     2017-11-03 09:38:24   TotalUsableCapacity 7357 
     2017-11-03 09:38:24   Ullage          69 
     2017-11-02 10:35:41   state           opened 
Attributes: 
   room       Heizöl`

I was thinking about Humidity 

`attr <tempHum> genericDeviceType thermometer
  attr <tempHum> homebridgeMapping [CurrentTemperature=temperature1] CurrentRelativeHumidity=<device2>:humidity`

but how?

**Comment by justme-1968** [comment]
just use the real device name(s) and the real reading names. if you just want one device with the percentage value use genericDevice type HumiditySensor and CurrentRelativeHumidity=<reading> with <reading> replaced by the name of the reading.

**Comment by theo-69** [comment]
thanks for the help I did 

`attr ecometer genericDeviceType HumiditySensor`

and then

`attr ecometer homebridgeMapping CurrentRelativeHumidity=TotalUsableCapacity:humidity`

The sensor shows, however it shows 0%

**Comment by theo-69** [comment]
In FHEM it shows in ecometer


genericDeviceType | HumiditySensor 

homebridgeMapping | CurrentRelativeHumidity=RemainingUsablePercent:humidity

**Comment by justme-1968** [comment]
is the reading rally humidity? for the water level reader?

**Comment by theo-69** [comment]
no its percent of the water level. The ecometer is reading the water level in my watertank. I just thought this would do the trick.

**Comment by theo-69** [comment]
Okay found the problem, used
`attr ecometer homebridgeMapping CurrentRelativeHumidity=TotalUsableCapacity`
and its working now, how can I add the temperature with separate icon?
