### ISSUE TITLE
WaterLevel

### ISSUE THREAD

**Issue by theo-69** [justme-1968/homebridge-fhem#43]
It locks like Homebridge WaterLevel is missing:

`/**
 * Characteristic "Water Level"
 */

Characteristic.WaterLevel = function() {
  Characteristic.call(this, 'Water Level', '000000B5-0000-1000-8000-0026BB765291');
  this.setProps({
    format: Characteristic.Formats.FLOAT,
    maxValue: 100,
    minValue: 0,
    perms: [Characteristic.Perms.READ, Characteristic.Perms.NOTIFY]
  });
  this.value = this.getDefaultValue();
};

inherits(Characteristic.WaterLevel, Characteristic);

Characteristic.WaterLevel.UUID = '000000B5-0000-1000-8000-0026BB765291';
`

**Comment by justme-1968** [comment]
it is at least in the latest homebridge version. just update homebridge and use genericDeviceType WaterLevel. no change to homebridge-fhem is needed.

**Comment by theo-69** [comment]
it says `ecometer: service name WaterLevel unknown
`

**Comment by justme-1968** [comment]
then the HAP-NodeJS version ist not up to date. check .../HAP-NodeJS/lib/gen/HomeKitTypes.js if WaterLevel is mentioned.

make sure you check the correct path as there may be multiple NodeJS versions on your system.

**Comment by theo-69** [comment]
Cant finde the HomeKitTypes.js, however all is up to date..

**Comment by theo-69** [comment]
Do I need to separate install HAP-NodeJS, i thought its part of homebridge!

**Comment by justme-1968** [comment]
yes. ist is part of the homebridge install.

but make sure it is installed only once as part of the correct homebridge version.

**Comment by theo-69** [comment]
strange tryed everything, it shows like a switch and if you look for details you can see with in the switch Waterlevel 80%, therefor FHEM is some how mapping it wrong
`[2018-2-16 11:50:43] [FHEM] ecometer: service name WaterLevel unknown
`
