### ISSUE TITLE
Define manufacturer, model and serial number

### ISSUE THREAD

**Issue by MobiusOne91** [justme-1968/homebridge-fhem#46]
Hi there,

I would like to add manufacturer, model and serial number informations to my FHEM devices. I know the different characteristics values, but I'm not able to change them. I think that I'm doing it wrong, but I'm not sure how to correct them. 

Characteristics:
Manufacturer: 00000020-0000-1000-8000-0026BB765291
Model: 00000021-0000-1000-8000-0026BB765291
Serial Number:00000030-0000-1000-8000-0026BB765291

Inside FHEM I configured Homebridgemappings as follows:
00000020-0000-1000-8000-0026BB765291=Manufacturer,name=manufacturer,format=STRING
00000021-0000-1000-8000-0026BB765291=Model,name=model,format=STRING
00000030-0000-1000-8000-0026BB765291=Serialnumber,name=serialnumber,format=STRING

Sadly it isn't working. Home App it still shows as unknown. Is this hardcoded inside this plugin?

**Comment by volschin** [comment]
More or less sadly it is. You can specify a special named reading to include the serial number, but it cannot be set by homebridge mapping field.

**Comment by justme-1968** [comment]
it will be implemented in the next update. 

but i'm currently quite busy and it will take a little while.

**Comment by MobiusOne91** [comment]
That would be really awesome. Thanks for the info!
