### ISSUE TITLE
genericDeviceType ValveType.GENERIC_VALVE

### ISSUE THREAD

**Issue by theo-69** [justme-1968/homebridge-fhem#48]
Hallo ich wollte `genericDeviceType` als Wasserhahn zuordnen leider bekomme ich es nicht hin laut HAP-NodeJS müsste es bei HomeKit `ValveType.GENERIC_VALVE` oder `ValveType=0` sein aber wenn ich die nutze wird er mir in Home nicht als Wasserhahn sondern als Schalter angezeigt.

**Comment by justme-1968** [comment]
das mapping für ein ventil muss etwa so aussehen:
```
genericDeviceType Valve

clear Active=state,values=off:INACTIVE;/.*/:ACTIVE InUse=state,values=off:0;/.*/:1,readOnly=1 ValveType=type,default=GENERIC_VALVE
```
die readings und kommandos musst du anpassen. 



ein wasserhahn mit zeit steuerung schaut etwa so aus: 
```
genericDeviceType Valve

homebridgeMapping clear Active=state,values=off:INACTIVE;/.*/:ACTIVE,cmds=ACTIVE:on-2;INACTIVE:off InUse=state,values=off:0;/.*/:1,readOnly=1 ValveType=type,default=WATER_FAUCET RemainingDuration=timerRemaining,maxValue=21600 SetDuration=timerDuration,maxValue=21600
```
hier musst du ebenfalls die kommandos und readings anpassen. duration ist hier ein reading in das fhem die rest laufzeit schreibt.

**Comment by theo-69** [comment]
Danke, hat schon etwas geholfen gibt es auch die Möglichkeit den Wasserhahn mit Prozent zu bedienen anzuzeigen?

**Comment by justme-1968** [comment]
nein. die ganzen bewässerungs characteristics können nur auf oder zu sein. die menge lässt sich nur über die zeit steuern. nicht über den durchfluss. die gängigen magnet- und kugelventile können glaube ich auch nur auf oder zu.
