### ISSUE TITLE
New Homekit types TV, Receivers, Speakers,...

### ISSUE THREAD

**Issue by Gruni22** [justme-1968/homebridge-fhem#54]
First of all I want to thank you for your great work!!!
I really like homebridge-fhem. 

Would it be possible to create mappings for TV, Receivers, Speaker services?

**Comment by justme-1968** [comment]
they are already included :) . see this example here: https://wiki.fhem.de/wiki/Homebridge_einrichten#BRAVIA_Fernseher

the only thing currently not working is the channel selection and i have no idea why...
i think there is a problem with linking the characteristics.

**Comment by Gruni22** [comment]
That is a bad thing...

**Comment by justme-1968** [comment]
just had another test with the current beta 5 and now it basically works.

i will add a version that is configureable through the homebridgeMapping for the next update.

**Comment by justme-1968** [comment]
update is published. input selection works. see bravia example in the fhem wiki.

have fun ;)

**Comment by Kolbi** [comment]
genericDeviceType Television is not available in FHEM?

**Comment by justme-1968** [comment]
it is. just set it manually.

example here: https://wiki.fhem.de/wiki/Homebridge_einrichten#BRAVIA_Fernseher
