### ISSUE TITLE
Homekit type valve

### ISSUE THREAD

**Issue by Tobias007** [justme-1968/homebridge-fhem#56]
Hi, habe versucht einen Wasserhahn zu mappen. Allerdings ist der GenericDeviceType Valve nicht in der index.js enthalten. Ich habe diesen u.a. hier hinzugefuegt:

    var serviceNameOfGenericDeviceType = {      ignore: null,
                                              security: 'SecuritySystem',
                                                switch: 'Switch',
                                                outlet: 'Outlet',
                                                 light: 'Lightbulb',
                                                 blind: 'WindowCovering',
                                               contact: 'ContactSensor',
                                           thermometer: 'TemperatureSensor',
                                            thermostat: 'Thermostat',
                                                garage: 'GarageDoorOpener',
                                                window: 'Window',
                                                  lock: 'LockMechanism',
                                             valve: 'Valve'

                                         };

nun wird das Wasserhahn symbol angezeigt, allerdings wenn man den Wasserhahn einschalten moechte, erscheint nur "Starten..." und das Symbol kreiselt --  statt "Ein".

Habe folgendes mapping:
genericDeviceType Valve

clear Active=state,values=off:INACTIVE;/.*/:ACTIVE InUse=state,values=off:0;/.*/:1,readOnly=1 ValveType=type,default=GENERIC_VALVE

**Comment by justme-1968** [comment]
einfach von hand  `attr <name> genericDeviceType Valve` in der command box setzen. es muss im code nichts geändert werden.

/./ matched genau auf ein zeichen. /.*/ ist richtiger.

du hast keine cmds in deinem mapping gesetzt.

wenn es wirklich ein wasserhahn ist: WATER_FAUCET statt GENERIC_VALVE ist vermutlich  besser.

ein funktionierendes mapping für einen hm autor schaut z.b. so aus: `clear Active=state,values=off:INACTIVE;/.*/:ACTIVE,cmds=ACTIVE:on;INACTIVE:off InUse=state,values=off:0;/.*/:1,readOnly=1 ValveType=type,default=WATER_FAUCET
`

**Comment by Tobias007** [comment]
Danke und sorry fuer die späte Rückmeldung! Funktioniert mittlerweile bestens!
