### ISSUE TITLE
Homebridge isn't recheable after install fhem plugin

### ISSUE THREAD

**Issue by flonatural** [justme-1968/homebridge-fhem#59]
hello,

like i said in the title, if I install this Plugin my Homebridge goes alltime unrecheable and i really dont know why. I tried all the tipps from the www but no chance. Maybe someone else have the same probs.

**Comment by justme-1968** [comment]
what is in the log?

what device have you included?

**Comment by flonatural** [comment]
homebridge log says nothing all is good. 

I included some dummys, hue, ROLLO, aqara sensor (zigbee2mqtt).

**Comment by justme-1968** [comment]
start with a single device (maybe the dummy) and work your way up to see which device is responsible for the problem. probably there is a mapping that results in a configuration that homekit will reject.

**Comment by flonatural** [comment]
now it works seems like one of my hue lights wasnt on and fhem denied then evrything rly sad but now it works thank you
