### ISSUE TITLE
Zigbee2mqtt Farbe setzen mit Homebridge (homebridgeMapping)

### ISSUE THREAD

**Issue by Sonsi79** [justme-1968/homebridge-fhem#64]
Hi @justme-1968 ,
danke für Deine viele und tolle Arbeit mit dem Plugin!

Ich habe gesehen dass Du automatisch readings wie "hue","bri" etc. abgreifst und diese für das homebridge_mapping verwendest.
Ich nutze zigbee2mqtt und dort werdend z.B. die farbigen Hue oder Osram Lampen anders in ihren FHEMreadings hinterlegt als via in FHEM eingebundener Phillips Bridge.
Hierdurch greift der Automatismus in deinem Plugin nicht und ich finde keine Lösung um die Farbe vie Home app zu ändern.

Ist es möglich die automatische reading Übernahme entsprechend zu erweitern oder hast Du alternativ einen Tip wie ich es manuell ins "homebridgeMapping" angeben kann?

Meine Readings einer farbigen Phillips Hue Lampe sind:
brightness 18
color_hue 46.2
color_mode 2
color_saturation 55.1
color_temp 366
color_x 0.457
color_y 0.41
state ON

Danke und beste Grüße
Christoph

**Comment by justme-1968** [comment]
bitte schau mal im forum. da sollte es einige lösungen geben. ich glaube sogar ein attrTemplate.  
                                                                                                     
das problem mit mqtt ist das es leider nicht so standardisiert ist wie man es sich wünschen würde.

**Comment by Sonsi79** [comment]
Ich gebe auf. Finde einfach nicht die passende Lösung.
Ich muss dem Zigbee2mqtt die Farbe als HEX übermitteln aber bekomme es einfach nicht "übersetzt" für die Homebridge.

Vielleicht noch jemand das Problem und eine Lösung oder Idee?

**Comment by wiresio** [comment]
Das Problem wird u.a. hier diskutiert - noch ohne Lösung: https://forum.fhem.de/index.php/topic,96783.0.html

Wäre ebenfalls interessiert.

**Comment by justme-1968** [comment]
siehe hier: https://forum.fhem.de/index.php/topic,115677.msg1099510.html#msg1099510 bzw. die lösung hier: https://forum.fhem.de/index.php/topic,70738.msg695300.html#msg695300

**Comment by wiresio** [comment]
@Sonsi79 - eine funktionierende Lösung für eine Osram AA69697 / Classic A60 RGBW, die via zigbee2mqtt angebunden ist, findest Du hier: https://forum.fhem.de/index.php/topic,96783.msg1111565.html#msg1111565
