### ISSUE TITLE
Add ZWave dimmers

### ISSUE THREAD

**Issue by vogon1** [justme-1968/homebridge-fhem#7]
Hi,

The following diff adds ZWave dimmers; I will try to add some ZWave sensors as well.

```
022c1022,1036
<   if( match = s.PossibleSets.match(/(^| )pct\b/) ) {
---
>   if( match = s.PossibleSets.match(/(^| )dim:slider,0,1,99/) ) {
>     // ZWave dimmer
>     this.service_name = 'light';
>     this.mappings.On = { reading: 'state', valueOff: '0', cmdOn: 'on', cmdOff: 'off' };
>     this.mappings.Brightness = { reading: 'state', cmd: 'dim', delay: true };
>
>     this.mappings.Brightness.reading2homekit = function(mapping, orig) {
>       var match;
>       if( match = orig.match(/dim (\d+)/ ) )
>         return parseInt( match[1] );
>
>       return 0;
>     }.bind(null, this.mappings.Brightness);
>
>   } else if( match = s.PossibleSets.match(/(^| )pct\b/) ) {
```

Sietse

**Comment by justme-1968** [comment]
thanks. i have included your patch.

regarding additional devices and sensors: i'm happy to include them following the idea to add mainly things that would require special reading2homekit and homekit2reading functions that can not be configured directly by the homebridgeMapping attribute but only by using jsFunctions and some custom code.

'simple' devices with just a reading that could also be set by homebridgeMapping and also multipurpose devices with many different readings and functions that are probably quite individual should better be configured by the homebridgeMapping attribute which is quite powerful.

so: thinks that require coding should be included in the code, things that just require configuration of reading names should probably only in the code if it affects more than one device and normally be configured by the homebridgeMapping attribute.

  andre
