### ISSUE TITLE
Cant chnage TargetTemperature

### ISSUE THREAD

**Issue by B4ngB4ng** [justme-1968/homebridge-fhem#74]
https://github.com/justme-1968/homebridge-fhem/blob/bc5bbb5ee2e46d5c3858df110ae7b5a1c67cb824/index.js#L1957

After deleteing ("delete this.mappings.TargetTemperature;") its possibel to set the TargetTemperature

**Comment by justme-1968** [comment]
you should probably fix the reason for the error message you are seeing instead of removing the delete.

make sure your command exists in the device.

**Comment by B4ngB4ng** [comment]
Yah the TargetTemperature exists everything works fine after deleting this line ... so what else can i check ?

**Comment by justme-1968** [comment]
i think the device in fhem is not reporting its set command correctly.

please show a jsonlist2 from the device.

**Comment by SirBen88** [comment]
I posted this also in the FHEM forum:
`{
  "Arg":"Thermostat_Badezimmer",
  "Results": [
  {
    "Name":"Thermostat_Badezimmer",
    "PossibleSets":" ",
    "PossibleAttrs":"alias comment:textField-long eventMap:textField-long group room suppressReading userReadings:textField-long verbose:0,1,2,3,4,5 disable disabledForIntervals readingList setExtensionsEvent:1,0 setList useSetExtensions event-aggregator event-min-interval event-on-change-reading event-on-update-reading oldreadings stateFormat:textField-long timestamp-on-change-reading DbLogExclude DbLogInclude DbLogValueFn:textField-long cmdIcon devStateIcon devStateIcon:textField-long devStateStyle genericDeviceType:security,ignore,switch,outlet,light,blind,thermometer,thermostat,contact,garage,window,lock,IrrigationSystem,Speaker,television,Valve homebridgeMapping:textField-long icon siriName sortby webCmd webCmdLabel:textField-long widgetOverride model userattr",
    "Internals": {
      "FUUID": "5d05cda0-f33f-2b06-a343-e2bb09c58fef870c",
      "NAME": "Thermostat_Badezimmer",
      "NR": "63",
      "STATE": "???",
      "TYPE": "dummy"
    },
    "Readings": {      "state": { "Value":"???", "Time":"2019-08-25 07:51:14" } },
    "Attributes": {
      "genericDeviceType": "thermostat",
      "homebridgeMapping": "TargetTemperature=MYSENSOR_0:hvacsetpointheat15,cmd=hvacsetpointheat15,minValue=18,maxValue=26,minStep=0.5,nocache=1\nCurrentTemperature=MYSENSOR_0:temperature14,nocache=1\nCurrentRelativeHumidity=MYSENSOR_0:humidity13,nocache=1\nCurrentHeatingCoolingState=MYSENSOR_0:status15,values=off:0;;on:1;;cool:2,nocache=1\nTargetHeatingCoolingState=MYSENSOR_0:status15,values=off:0;;on:1;;cool:2,nocache=1",
      "model": "Badezimmer",
      "room": "Homebridge",
      "siriName": "Thermostat",
      "userattr": "model"
    }
  }  ],
  "totalResultsReturned":1
}`

**Comment by SirBen88** [comment]
I think it has something to do with this line (1954):
`!s.PossibleSets.match('(^| )'+this.mappings.TargetTemperature.cmd+'\\b')`

If this is deleted, no error/warning and everything works great.

**Comment by justme-1968** [comment]
your PossibleSets in the jsonlist is empty. this is wrong and should be fixed. also fhemweb will not display a set dropdown.
