### ISSUE TITLE
Plugin slows down Homebridge 1.3

### ISSUE THREAD

**Issue by Hansjshx** [justme-1968/homebridge-fhem#75]
After updating Homebridge to version 1.3.0 I get this error message:
 
`This plugin slows down Homebridge. The read handler for the characteristic 'LastActivation' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.`

Creating a Child Bridge fails.

**Comment by justme-1968** [comment]
there should be more in the log immediately before this message.

i have just pushed an update which should fix this warning.

**Comment by webdandy** [comment]
I also have these messages with version homebridge-fhem v0.5.24.
