### ISSUE TITLE
Installation procedure failure (version 0.5.29)

### ISSUE THREAD

**Issue by steff38** [justme-1968/homebridge-fhem#78]
When I try to install the latest version (0.5.29), I get the following error message:

![CD79BC3D-0B69-4390-8F34-0917C906D2DF](https://user-images.githubusercontent.com/79751845/111835527-5affa300-88f5-11eb-99ea-6275473d38a0.jpeg)

Would it be possible to solve the issue? Before this version I never had problems installing updates.

Thx, stef

**Comment by justme-1968** [comment]
i'm pretty sure this is not related to homebridge-fhem but to npm. please remove the directory in question and try again.

**Comment by steff38** [comment]
Thx for the reply. I deleted the folder /.homebridge-fhem-rUwdsCQx and the update ran without problems.

**Comment by justme-1968** [comment]
try to remove the complete /usr/lib/homebridge-fhem directory.
