### ISSUE TITLE
No reconnect after FHEM Server restart

### ISSUE THREAD

**Issue by Hofyyy** [justme-1968/homebridge-fhem#81]
It seems to be that the "home bridge-fhem" plugin does not recover the connection after I rebooted my 2nd raspberry with the real FHEM Server. If I reboot the home bridge process all works fine again.

Pi-1: Homebridge + FHEM Plugin
Pi-2: FHEM Server (with 8 Blinds) 

Are their special settings or is that a known behavior?

**Comment by justme-1968** [comment]
please set neverTimeout to true.

**Comment by Hofyyy** [comment]
If you have some time a documentation for this would be great.
So what does this setting do in detail? When is the normal timeout?

In my usecase I did only a restart of the FHEM Server. So we talk about 1 min at maximum.
I think if you have lets say 15 mins no connection to the FHEM server. Detailed warnings in the log would be great anyway.
