### ISSUE TITLE
Issue with harmony device

### ISSUE THREAD

**Issue by ABrolund** [justme-1968/homebridge-fhem#9]
Hi, 
I have four harmony devices declared in FHEM, three of them are listed by homebridge-fhem without any problem. But the fourth which is the same in declaration is missing. 
How is the best way to debug and find the root cause, which i still suspect on my side?

Best 
Andreas

**Comment by justme-1968** [comment]
please show a list of the four devices in fhem and the console output when starting homebridge with --debug

**Comment by ABrolund** [comment]
Hi, 
sorry for late answer. My findings: It has nothing to do with the declaration itself. 
I removed the device then restarted homebridge. After readding it and another restart of homebridge the device showed up and is working fine now. 
I am not able to reproduce, so I suggest to close this issue for the time being

**Comment by justme-1968** [comment]
ok. closing this for now.
