### ISSUE TITLE
Plugin settings in Homebridge UI overwrite manually created configuration

### ISSUE THREAD

**Issue by kennymc-c** [justme-1968/homebridge-fhem#92]
If you use a manually created configuration and then adjust a parameter in the plugin's Homebridge UI settings page, the previously created configuration is overwritten. Parameters not supported in the UI, such as ssl and auth, are deleted from the configuration and have to be added again manually.

**Comment by justme-1968** [comment]
i have added the missing ssl and auth options for homebridge-config-ui

**Comment by kennymc-c** [comment]
If I separate username and password as specified with a colon, this is also transferred as a string into the config. But this is the wrong format and causes an error message on restart. It should be the following format:
```
{
"user": "user",
"pass": "password"
 }
```

**Comment by justme-1968** [comment]
you are right... it should be fixed now.
